image: debian:latest

before_script:
  - apt-get update -yqq
  - apt-get install -yqq perl make binutils findutils tar

pages:
  script:
    - make pages
  artifacts:
    paths:
      - public
  only:
    - master
