#!/bin/bash
#
# Copyright (C) 2005-2025 Gabriel Moreau <Gabriel.Moreau(A)univ-grenoble-alpes.fr>
# License GNU GPL version 2 or later
#
# 2007/10/23 Gabriel Moreau
# 2010/11/03 Gabriel Moreau
# 2011/03/30 Gabriel Moreau - make it generic
# 2017/11/04 Gabriel Moreau - all reworks - use tab

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export LANG=C

SITE_NAME=''
REMOTE_SERVER=localhost
REMOTE_USER=''
REMOTE_FOLDER=/var/www/klask/
KEEP_MAX=180

GRAPH_MODULO=9
GRAPH_SHIFT=1

CACHE_TIMEOUT=50
CACHE_FOLDER='/tmp/klask-push-web'

if [ -f /etc/klask/push-web.conf ]
then
   . /etc/klask/push-web.conf
fi


# remote command
DOT=/usr/bin/dot

mkdir -p ${CACHE_FOLDER}
if [ ! -d ${CACHE_FOLDER} ]
then
   echo "Error: Folder ${CACHE_FOLDER} do not exist !"
   exit 1
fi
cd ${CACHE_FOLDER}

LOCALTIME=$(date "+%Y-%m-%d %H:%M")
TIMEFILE=$(date "+%Y-%m-%d.%H-%M")

find ${CACHE_FOLDER}/ -type f -a -mtime +${CACHE_TIMEOUT} -delete

klask exportsw --format dot --modulo ${GRAPH_MODULO} --shift ${GRAPH_SHIFT} > ${CACHE_FOLDER}/switch-map.txt.new
klask exportsw                                                              > ${CACHE_FOLDER}/switch-db.txt.new

klask exportdb    > ${CACHE_FOLDER}/hostname-db.txt
klask ip-free     > ${CACHE_FOLDER}/ipfree-db.txt
klask bad-vlan-id > ${CACHE_FOLDER}/badvlan-db.txt

cmp --silent ${CACHE_FOLDER}/switch-db.txt.new ${CACHE_FOLDER}/switch-db.txt || {
   mv -f ${CACHE_FOLDER}/switch-db.txt.new ${CACHE_FOLDER}/switch-db.${TIMEFILE}.txt;
   ln -sf switch-db.${TIMEFILE}.txt ${CACHE_FOLDER}/switch-db.txt
   }

cmp --silent ${CACHE_FOLDER}/switch-map.txt.new ${CACHE_FOLDER}/switch-map.txt || {
   mv -f ${CACHE_FOLDER}/switch-map.txt.new ${CACHE_FOLDER}/switch-map.${TIMEFILE}.txt;
   ln -sf switch-map.${TIMEFILE}.txt ${CACHE_FOLDER}/switch-map.txt
   }

# keep trace of old switch map
old_switch_db=$((echo 'command <tt>klask exportsw --format txt</tt>';
      (cd ${CACHE_FOLDER}/; ls -1 switch-db.20[0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9][0-9]-[0-9][0-9].txt;) \
      | sed -e 's/^switch-db\.//; s/\.txt$//;' \
      | xargs -r -I {} printf " <a href=\"switch-db.%s.txt\">%s</a>\n" '{}' '{}' \
      ) \
   | paste -sd ',' -)

old_switch_map=$((echo 'graphviz';\
      (cd ${CACHE_FOLDER}/; ls -1 switch-map.20[0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9][0-9]-[0-9][0-9].txt;) \
      | sed -e 's/^switch-map\.//; s/\.txt$//;' \
      | xargs -r -I {} printf " <a href=\"switch-map.%s.txt\">%s</a>\n" '{}' '{}' \
      )\
   | paste -sd ',' -)


cat <<END > ${CACHE_FOLDER}/index.html
<!DOCTYPE html>
<html lang="en">
<head>
 <link rel="stylesheet" type="text/css" href="style-klask.css" />
 <!-- <meta http-equiv="refresh" content="1800"> -->
 <title>Klask mapping net-tools</title>
 <script src="sorttable-klask.js"></script>
 <script src="ui.js"></script>
</head>
<body>
<h1>
<b><a href="https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/klask" class="circle">Klask</a></b>
Tool for <a href="switch-map.png">mapping</a> the local network - site ${SITE_NAME}
<a class="refresh" href="./">${LOCALTIME}</a>
</h1>

<div id="navbar">
 <ul>
  <li class="selectableTabButton" data-tab="IP_detected" id="selected">IP detected</li>
  <li class="selectableTabButton" data-tab="IP_available">IP available</li>
  <li class="selectableTabButton" data-tab="VLAN_mismatch">VLAN mismatch</li>
  <li class="selectableTabButton" data-tab="MAP_png">MAP (png)</li>
  <li class="selectableTabButton" data-tab="MAP_svg">MAP (svg)</li>
  <li class="selectableTabButton" data-tab="RAW_data">RAW data</li>
 </ul>
</div>

<div id="content">

 <div id="IP_detected" class="selectableTabContent">
  <p>
  List of all IP addresses detected on the local network (on all VLANs)
  since the origin of the database
  (except those that have been deleted manually and voluntarily).
  </p>
END

klask exportdb --format html >> ${CACHE_FOLDER}/index.html

cat <<END >> ${CACHE_FOLDER}/index.html
 </div>

 <div id="IP_available" class="selectableTabContent" style="display:none">
  <p>
  List all free IP addresses (which have never been used or not used for two years).
  These IP addresses are available to assign to all new computers.
  </p>
END

klask ip-free --format html >> ${CACHE_FOLDER}/index.html

cat <<END >> ${CACHE_FOLDER}/index.html
 </div>

 <div id="VLAN_mismatch" class="selectableTabContent" style="display:none">
  <p>
  List all computers connected to switches where the VLAN is misconfigured.
  Returns the port and VLAN to configure on these switches.
  </p>
END

klask bad-vlan-id --format html >> ${CACHE_FOLDER}/index.html

cat <<END >> ${CACHE_FOLDER}/index.html
 </div>

 <div id="MAP_png" class="selectableTabContent" style="display:none">
   <p>
   Direct link to local network map in the formats <a href="switch-map.png">png</a> and <a href="switch-map.svg">svg</a>.
   Because the map could be big,
   you will have a better web experience with
   <a href="https://addons.mozilla.org/fr/firefox/addon/zoom-image/">Image Zoom<a> plugin (or equivalent) installed.
   </p>
   <a href="switch-map.png"><img class="map" src="switch-map.png"></a>
 </div>

 <div id="MAP_svg" class="selectableTabContent" style="display:none">
   <p>
   Direct link to local network map in the formats <a href="switch-map.png">png</a> and <a href="switch-map.svg">svg</a>.
   </p>

   <embed type="image/svg+xml" src="switch-map.svg" id="embed-svg-map">
 </div>

 <div id="RAW_data" class="selectableTabContent" style="display:none">
  <p>
   The main raw results of Klask are accessible directly,
   via <tt>wget</tt> or <tt>curl</tt> tools for example,
   for any specific treatment:
   <ul>
    <li><a href="hostname-db.txt">Computers DB</a> (command <tt>klask exportdb --format txt</tt>),</li>
    <li><a href="switch-db.txt">Switches DB</a> (${old_switch_db}),</li>
    <li><a href="ipfree-db.txt">IP available</a> (command <tt>klask ip-free --format txt</tt>),</li>
    <li><a href="badvlan-db.txt">VLAN mismatch</a> (command <tt>klask bad-vlan-id --format txt</tt>),</li>
    <li>Map format: <a href="switch-map.txt">dot source</a> (${old_switch_map}), <a href="switch-map.png">png</a>, <a href="switch-map.svg">svg</a>.</li>
   </ul>
  </p>
 </div>
</div>

<p class="copyright">
Klask (version $(klask version | grep ^Version | cut -f 2 -d ' ')) - $(klask version | grep ^Copyright | cut -f 1 -d '<')
</p>
<!-- Try to prefect switch map image -->
<link rel="prefetch" href="switch-map.png">
</body>
</html>
END

if [ "${REMOTE_SERVER}" = "localhost" ]
then
   rsync --times \
      /usr/share/klask/sorttable-klask.js \
      /usr/share/klask/svg-pan-zoom.js \
      /usr/share/klask/ui.js \
      /usr/share/klask/style-klask.css \
      ${CACHE_FOLDER}/index.html \
      ${CACHE_FOLDER}/*-db.txt \
      ${CACHE_FOLDER}/switch-map.txt \
      ${CACHE_FOLDER}/*.20[0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9][0-9]-[0-9][0-9].txt \
      ${REMOTE_FOLDER}/

   [ -x ${DOT} ] && (cd ${REMOTE_FOLDER};
      [ switch-map.txt -nt switch-map.svg -o ! -s switch-map.svg -o ! -e switch-map.svg ] && ${DOT} -T svg switch-map.txt > switch-map.svg;
      [ switch-map.txt -nt switch-map.png -o ! -s switch-map.png -o ! -e switch-map.png ] && ${DOT} -T png switch-map.txt > switch-map.png)

else
   rsync --links --times \
      /usr/share/klask/sorttable-klask.js \
      /usr/share/klask/svg-pan-zoom.js \
      /usr/share/klask/ui.js \
      /usr/share/klask/style-klask.css \
      ${CACHE_FOLDER}/index.html \
      ${CACHE_FOLDER}/*-db.txt \
      ${CACHE_FOLDER}/switch-map.txt \
      ${CACHE_FOLDER}/*.20[0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9][0-9]-[0-9][0-9].txt \
      ${REMOTE_USER}@${REMOTE_SERVER}:${REMOTE_FOLDER}/


   ssh ${REMOTE_USER}@${REMOTE_SERVER} "(cd ${REMOTE_FOLDER};
      [ switch-map.txt -nt switch-map.svg -o ! -s switch-map.svg -o ! -e switch-map.svg ] && ${DOT} -T svg switch-map.txt > switch-map.svg;
      [ switch-map.txt -nt switch-map.png -o ! -s switch-map.png -o ! -e switch-map.png ] && ${DOT} -T png switch-map.txt > switch-map.png);
      find ${REMOTE_FOLDER} -name '*.txt' -a -mtime +${KEEP_MAX} -delete"
fi
